name: Validate Helm Chart

on:
  push:
    branches:
    - main

jobs:
  validate-chart:
    runs-on: ubuntu-latest

    steps:
    - name: validate
      run: |
        curl -L \
        "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest \
        | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
        sudo install terrascan /usr/local/bin && rm terrascan
        cd /home/student_03_a3205f7769ce/lab/terraform
        terrascan scan -i helm
